# Add this defaults list to integrate loguru with Hydra's logging
defaults:
  - hydra: default  # <-- This loads configs/Dyadic_GF/hydra/default.yaml
  - _self_

# ADD THIS SECTION to set a custom name for the output directory
hydra:
  job:
    name: Dyadic_GF_Sommerfeld
# --- Our Application Configuration ---

material:
  # Choose the source type: 'excel' for dispersive, 'constant' for non-dispersive
  source_type: excel

  # --- Settings for a CONSTANT material ---
  # This value is used only if source_type is 'constant'
  constant_value: 9.0+0.0j # Example for a non-dispersive material

  # --- Settings for an EXCEL-based material ---
  # This section is used only if source_type is 'excel'
  excel_config:
    filepath: "DielectricFunction/dielectric function.xlsx"
    sheet_name: "Ag_OMNN"

simulation:
  material: "Ag" # Material surface
  energy_eV: 
  # Emitter energy, unit in eV, can be a single value, dictionary, or list.
  #Examples:
  # Single value: 1.50 (int or float)
  # Dictionary: {min: 1.0, max: 3.0, points: 201} (for a range)
  # List: [1.0, 1.5, 2.0]
    min: 1.0
    max: 1.0 # Set min and max to the same value for a single point
    points: 1
  position:
    zD: 2.0e-9
    zD_nm: 2 # Key for name
    zA: 2.0e-9
    Rx_nm: # New section to define the range of horizontal distances
      start: 0.0
      stop: 500.0
      points: 501 # This will give you points 1, 2, 3, ..., 1000

output:
  filename: "result_${simulation.material}_${simulation.position.zD_nm}_nm.hdf5"