#plotting configuration for sqrt MSD vs time
defaults:
  - hydra: default  # <-- 
  - _self_
# Where to put the PNG (Hydra will create a run dir)
hydra:
  job:
    name: plot_msd

# One or more curves to draw on the same axes
# Each curve: either give absolute 'path', or set 'use_latest_glob' (relative to MQED_ROOT/PWD)
curves:
  # - label: "Magic-Angle"
  #   use_latest_glob: "${oc.env:MQED_ROOT,${hydra:runtime.cwd}}/data/QDyn_cache/silver_stationary_latest.hdf5"  # or using "outputs/Lindblad/.../qdyn_result.hdft"
  #   style: "-"         # matplotlib line format
  #   lw: 1.5
  
  # - label: "σ=10"
  #   use_latest_glob: "${oc.env:MQED_ROOT,${hydra:runtime.cwd}}/data/QDyn_cache/silver_sigma10_avg_latest.hdf5" # or using "outputs/NHSE_disorder/.../qdyn_disorder_avg.hdft"
  #   style: "-"         # e.g., "C1-"
  #   lw: 1.5
  # - label: "σ=30"
  #   use_latest_glob: "${oc.env:MQED_ROOT,${hydra:runtime.cwd}}/data/QDyn_cache/silver_sigma30_avg_latest.hdf5" # or using "outputs/NHSE_disorder/.../qdyn_disorder_avg.hdft"
  #   style: "-"         # e.g., "C1-"
  #   lw: 1.5
  # - label: "σ=50"
  #   use_latest_glob: "${oc.env:MQED_ROOT,${hydra:runtime.cwd}}/data/QDyn_cache/silver_sigma50_avg_latest.hdf5" # or using "outputs/NHSE_disorder/.../qdyn_disorder_avg.hdft"
  #   style: "-"         # e.g., "C1-"
  #   lw: 1.5


  - label: "Fresnel"
    use_latest_glob: "${oc.env:MQED_ROOT,${hydra:runtime.cwd}}/data/QDyn_cache/height_2nm/Fresnel_silver_planar_665nm_N100_height_2nm_inter_3nm.hdf5"  # or using "outputs/Lindblad/.../qdyn_result.hdft"
    style: "-"         # matplotlib line format
    lw: 2
  - label: "BEM"
    use_latest_glob: "${oc.env:MQED_ROOT,${hydra:runtime.cwd}}/data/QDyn_cache/height_2nm/BEM_silver_planar_665nm_N100_height_2nm_inter_3nm.hdf5"  # or using "outputs/Lindblad/.../qdyn_result.hdft"
    style: "r--"         # matplotlib line format
    lw: 2

  # - label: "planar"
  #   use_latest_glob: "${oc.env:MQED_ROOT,${hydra:runtime.cwd}}/data/QDyn_cache/intermol_8nm/Fresnel_silver_planar_665nm_N30.hdf5"  # or using "outputs/Lindblad/.../qdyn_result.hdft"
  #   style: "-"         # matplotlib line format
  #   lw: 2

  # - label: "planar_NN"
  #   use_latest_glob: "${oc.env:MQED_ROOT,${hydra:runtime.cwd}}/data/QDyn_cache/intermol_8nm/Fresnel_silver_planar_665nm_N30_NN.hdf5"  # or using "outputs/Lindblad/.../qdyn_result.hdft"
  #   style: "--"         # matplotlib line format
  #   lw: 2

  # - label: "nanorod"
  #   use_latest_glob: "${oc.env:MQED_ROOT,${hydra:runtime.cwd}}/data/QDyn_cache/intermol_8nm/BEM_silver_nanorod_665nm_N30.hdf5"  # or using "outputs/Lindblad/.../qdyn_result.hdft"
  #   style: "-"         # matplotlib line format
  #   lw: 2
  
  # - label: "nanorod_NN"
  #   use_latest_glob: "${oc.env:MQED_ROOT,${hydra:runtime.cwd}}/data/QDyn_cache/intermol_8nm/BEM_silver_nanorod_665nm_N30_NN.hdf5"  # or using "outputs/Lindblad/.../qdyn_result.hdft"
  #   style: "-."         # matplotlib line format
    # lw: 2

  # - label: "free space"
  #   use_latest_glob: "${oc.env:MQED_ROOT,${hydra:runtime.cwd}}/data/QDyn_cache/height_8nm/Fresnel_vacuum_planar_665nm_N50.hdf5"  # or using "outputs/Lindblad/.../qdyn_result.hdft"
  #   style: "-."         # matplotlib line format
  #   lw: 1.4


plot_settings:
  save_plot: true
  geometry: planar # or other geometries, 'sphere', 'planar', etc.
  material: silver
  excitation_position_nm: initial # or 'initial', 'middle', etc.
  filename: "${plot_settings.geometry}_${plot_settings.material}_${plot_settings.excitation_position_nm}_msd_comparison.png"
  dpi: 400
  show: false
  tight_layout: true
  grid: false # Enable grid for true, or False to disable
  legend: true # set to true to show legend
  figsize: [8.0, 6.0] # width, height in inches (1 inch = 2.54 cm) [3.35,2.4] for ACS

  # x selection (time). Choose one: x_range_ps or x_index_range
  x_range_ps: [0.0, 150.0]   # in picoseconds
  # x_index_range: [0, 500]

  # axis labels, scales, limits
  xlabel: "t (ps)"            # or "t (ps)" if you keep in ps
  ylabel: "MSD (nm$^2$)"
  title: null # or make your own title, "Silver; Middle Excitation"
  xscale: linear             # or "log"
  yscale: linear
  xlim: [0,150]     # e.g., [0, 100]; use Null for automatic limit  
  ylim: [0, Null]        # e.g., [0, 100]; use Null for automatic limit

  font:
    family: null        # e.g. "DejaVu Sans", "Times New Roman"; null keeps default
    labelsize: 18
    ticksize: 18
    legendsize: 18
    titlesize: 18
    labelweight: bold   # "normal" or "bold"
    legendweight: bold  # "normal" or "bold"
    tickweight: bold     # "normal" or "bold"

  # optional multiply time axis (e.g., to show ×10^-10 s visually):
  x_scale_factor: 1.0        # keep 1.0 if you already saved 't_ps' in seconds; use 1e-12 to convert ps→s
  lw: 1.6
