#plotting configuration for sqrt MSD vs time
defaults:
  - hydra: default  # <-- 
  - _self_
# Where to put the PNG (Hydra will create a run dir)
hydra:
  job:
    name: plot_msd

# One or more curves to draw on the same axes
# Each curve: either give absolute 'path', or set 'use_latest_glob' (relative to MQED_ROOT/PWD)
curves:
  # - label: "Magic-Angle"
  #   use_latest_glob: "${oc.env:MQED_ROOT,${hydra:runtime.cwd}}/data/QDyn_cache/silver_stationary_latest.hdf5"  # or using "outputs/Lindblad/.../qdyn_result.hdft"
  #   style: "-"         # matplotlib line format
  #   lw: 1.5
  
  # - label: "σ=10"
  #   use_latest_glob: "${oc.env:MQED_ROOT,${hydra:runtime.cwd}}/data/QDyn_cache/silver_sigma10_avg_latest.hdf5" # or using "outputs/NHSE_disorder/.../qdyn_disorder_avg.hdft"
  #   style: "-"         # e.g., "C1-"
  #   lw: 1.5
  # - label: "σ=30"
  #   use_latest_glob: "${oc.env:MQED_ROOT,${hydra:runtime.cwd}}/data/QDyn_cache/silver_sigma30_avg_latest.hdf5" # or using "outputs/NHSE_disorder/.../qdyn_disorder_avg.hdft"
  #   style: "-"         # e.g., "C1-"
  #   lw: 1.5
  # - label: "σ=50"
  #   use_latest_glob: "${oc.env:MQED_ROOT,${hydra:runtime.cwd}}/data/QDyn_cache/silver_sigma50_avg_latest.hdf5" # or using "outputs/NHSE_disorder/.../qdyn_disorder_avg.hdft"
  #   style: "-"         # e.g., "C1-"
  #   lw: 1.5


  # - label: "Frensel"
  #   use_latest_glob: "${oc.env:MQED_ROOT,${hydra:runtime.cwd}}/data/QDyn_cache/Frensel_silver_stationary_665nm_N100.hdf5"  # or using "outputs/Lindblad/.../qdyn_result.hdft"
  #   style: "-"         # matplotlib line format
  #   lw: 1.5
  # - label: "BEM"
  #   use_latest_glob: "${oc.env:MQED_ROOT,${hydra:runtime.cwd}}/data/QDyn_cache/BEM_silver_stationary_665nm_N100.hdf5"  # or using "outputs/Lindblad/.../qdyn_result.hdft"
  #   style: "--"         # matplotlib line format
  #   lw: 1.5

  - label: "nanorod BEM"
    use_latest_glob: "${oc.env:MQED_ROOT,${hydra:runtime.cwd}}/data/QDyn_cache/BEM_silver_nanorod_665nm_N50.hdf5"  # or using "outputs/Lindblad/.../qdyn_result.hdft"
    style: "-"         # matplotlib line format
    lw: 1.5

  - label: "planar Frensel"
    use_latest_glob: "${oc.env:MQED_ROOT,${hydra:runtime.cwd}}/data/QDyn_cache/Frensel_silver_planar_665nm_N50.hdf5"  # or using "outputs/Lindblad/.../qdyn_result.hdft"
    style: "--"         # matplotlib line format
    lw: 1.5

plot_settings:
  save_plot: true
  geometry: nanorod # or other geometries, 'sphere', 'planar', etc.
  material: silver
  excitation_position_nm: middle # or 'initial', 'middle', etc.
  filename: "${plot_settings.geometry}_${plot_settings.material}_${plot_settings.excitation_position_nm}_msd.png"
  dpi: 400
  show: false
  tight_layout: true
  grid: false # Enable grid for true, or False to disable
  legend: true # set to true to show legend
  figsize: [7.5, 5.0]

  # x selection (time). Choose one: x_range_ps or x_index_range
  x_range_ps: [0.0, 150.0]   # in picoseconds
  # x_index_range: [0, 500]

  # axis labels, scales, limits
  xlabel: "t (ps)"            # or "t (ps)" if you keep in ps
  ylabel: "$MSD$ (nm$^2$)"
  title: null # or make your own title, "Silver; Middle Excitation"
  xscale: linear             # or "log"
  yscale: linear
  xlim: null
  ylim: null

  font:
    family: null        # e.g. "DejaVu Sans", "Times New Roman"; null keeps default
    labelsize: 12
    ticksize: 12
    legendsize: 12
    titlesize: 12
    labelweight: bold   # "normal" or "bold"
    legendweight: bold  # "normal" or "bold"

  # optional multiply time axis (e.g., to show ×10^-10 s visually):
  x_scale_factor: 1.0        # keep 1.0 if you already saved 't_ps' in seconds; use 1e-12 to convert ps→s
  lw: 1.5
