defaults:
  - _self_
  - hydra: default  # <-- 

hydra:
  job:
    name: compare_ez
log_file: ${hydra:runtime.output_dir}/${hydra.job.name}.log

paths:
  # lets you override with MQED_ROOT=/abs/path/to/repo
  root: ${oc.env:MQED_ROOT,${hydra:runtime.cwd}}
  data_dir: ${paths.root}/mqed/BEM

  dgf_h5: ${paths.data_dir}/Fresnel_result/result_const_50_nm.hdf5
  bem_plane_xlsx: ${paths.data_dir}/BEM_result/dipole_planar_results.xlsx
  bem_vacuum_xlsx: ${paths.data_dir}/BEM_result/dipole_vacuum_results.xlsx


dipole_frequency: 2.48  # example value (your units)

data:
  x_key: Rx_nm
  energy_index: 0

bem:
  sheet: FieldLine
  re_col: Re_Ez
  im_col: Im_Ez

dipoles:
  donor: {theta_deg: 0.0, phi_deg: 0.0}
  acceptor: {theta_deg: 0.0, phi_deg: 0.0}

test:
  enabled: true
  rtol: 1e-3
  atol: 1e-6

plot:
  dpi: 140
  figsize: [11, 6]
  save: True
  save_path: ez_enhancement.png

  rcParams:
    font.size: 18
    axes.labelsize: 26
    axes.titlesize: 22
    legend.fontsize: 22
    xtick.labelsize: 18
    ytick.labelsize: 18

  axes:
    title: " $\\omega_0$ = {dipole_frequency} $~\\mathrm{{eV}}$"
    xlabel: "Distance $R_x$ (nm)"
    ylabel: "Enhanc. of $E_z(\\omega_0)$"
    xlim: [0, 100]
    ylim: [0.8, 2.1]
    grid: false
    spine_width: 1.2

    ticks:
      direction: "in"
      top: true
      right: true
      labelsize: 18
      length: 6
      width: 1.2

  legend:
    loc: "center left"
    frameon: true
    fancybox: false
    framealpha: 1.0
    fontsize: 22
    edgecolor: "0.5"

  # what to draw first/last
  series_order: [bem_real, bem_imag, impl_real, impl_imag]

  series:
    bem_real:
      source: "bem_real"
      label: "Re $E_z$ (BEM)"
      linestyle: "None"
      marker: "o"
      markersize: 7
      markerfacecolor: "none"
      markeredgewidth: 1.6
      color: "m"

    bem_imag:
      source: "bem_imag"
      label: "Im $E_z$ (BEM)"
      linestyle: "None"
      marker: "s"
      markersize: 7
      markerfacecolor: "none"
      markeredgewidth: 1.6
      color: "c"

    impl_real:
      source: "impl_real"
      label: "Re $E_z$ (Analytical)"
      linestyle: "-"
      linewidth: 2.7
      color: "r"

    impl_imag:
      source: "impl_imag"
      label: "Im $E_z$ (Analytical)"
      linestyle: "-"
      linewidth: 2.7
      color: "b"
