defaults:
  - _self_
  - hydra: default  # <-- 

hydra:
  job:
    name: compare_bem_dyadic

io:
  xlsx_path: ${oc.env:MQED_ROOT,${hydra:runtime.cwd}}/mqed/BEM/BEM_GF_sample/dipole_silver_2nm_GF_60.xlsx
  sheet: DyadicG
  peff_csv: ${oc.env:MQED_ROOT,${hydra:runtime.cwd}}/mqed/BEM/BEM_GF_sample/peff_vs_lambda_30nm.csv
  fresnel_h5: ${oc.env:MQED_ROOT,${hydra:runtime.cwd}}/mqed/BEM/Frensel_result/result_Ag_2_nm.hdf5
  out_csv: bem_vs_fresnel.csv

sim:
  lambda_nm: 665.0
  interpolate_rx: true

compare:
  components: ["Gzz", "Gxz", "Gzx", "Gxx"]
