defaults:
  - _self_
  - hydra: default  # <-- 

hydra:
  job:
    name: reconstruct_GF
log_file: ${hydra:runtime.output_dir}/${hydra.job.name}.log

parameters:
  energy_eV: 1.864           # corresponds to lambda = 665 nm
  lambda_nm: 665             # wavelength in nm
  zD_nm: 8                     # dipole height in nm
  zA_nm: 8
  geometry: 'nanorod' # or 'nanorod', 'sphere', match with your simulation to avoid confusion.
  material: 'Ag'
  dipole_position_nm: 600    # dipole position along the nanorod axis in nm

io:
  xlsx_path: ${oc.env:MQED_ROOT,${hydra:runtime.cwd}}/data/BEM_cache/dipole_silver_nanorod_8nm_GF_665nm_pos_${parameters.dipole_position_nm}_height_8_0.xlsx
  peff_path: ${oc.env:MQED_ROOT,${hydra:runtime.cwd}}/data/BEM_cache/peff_vs_lambda_665nm.csv

  output_file: BEM_GF_${parameters.geometry}_${parameters.material}_${parameters.lambda_nm}nm_height_${parameters.zD_nm}nm_pos_${parameters.dipole_position_nm}nm.hdf5