defaults:
  - _self_
  - hydra: default  # <-- 

hydra:
  job:
    name: reconstruct_GF
log_file: ${hydra:runtime.output_dir}/${hydra.job.name}.log

parameters:
  energy_eV: 1.864           # corresponds to lambda = 665 nm
  lambda_nm: 665             # wavelength in nm
  zD_nm: 2.0
  zA_nm: 2.0
  geometry: 'nanorod' # or 'nanorod', 'sphere', match with your simulation to avoid confusion.
  material: 'Ag'

io:
  xlsx_path: ${oc.env:MQED_ROOT,${hydra:runtime.cwd}}/data/BEM_cache/YOUR_FILE.xlsx
  peff_path: ${oc.env:MQED_ROOT,${hydra:runtime.cwd}}/data/BEM_cache/YOUR_FILE.csv

  output_file: BEM_GF_${parameters.geometry}_${parameters.material}_${parameters.lambda_nm}.hdf5