defaults:
  - hydra: default
  - _self_

hydra:
  job:
    name: compute_ddi

ddi:
  gf_path: "outputs/result_Ag_2_nm.hdf5"   # path or your symlink/pointer
  energy_index: 0                          # int, [list], or "all"
  donor:
    theta_deg: 90
    phi_deg: 0
  acceptor:
    theta_deg: 90
    phi_deg: 0
  mu_D_debye: 3.8
  mu_A_debye: 3.8      # -1 => same as donor

output:
  dir: "outputs/ddi"
  save_mode: "per_energy"   # "per_energy" or "stack"
  filename: "ddi_stack.h5"  # used only when save_mode="stack"
  write_csv: true
