# Add this defaults list to integrate loguru with Hydra's logging
defaults:
  - hydra: default  # <-- This loads configs/Lindblad/hydra/default.yaml
  - _self_

# ADD THIS SECTION to set a custom name for the output directory
hydra:
  job:
    name: Lindblad
# --- Our Application Configuration ---

greens:
  h5_path: ${oc.env:MQED_ROOT,${oc.env:PWD}}/data/GF_cache/result_Ag_2_nm_latest.hdf5 # update as needed

#Material information
material:
  name: silver

# Simulation controls
simulation:
# time grid in picoseconds
  t_ps:
    start: 0.0
    stop: 150.0
    output_step: 5e-3


# system
  Nmol: 100 # number of sites
  d_nm: 3.0 # lattice spacing (nm)


# dipoles / orientation
  mu_D_debye: 3.8
  mu_A_debye: 3.8
  theta_deg: 90.0
  phi_deg: magic # or a number
  mode: stationary # or 'disorder'
  # disorder_sigma_phi_deg: 15.0 # uncomment for disordered orientations


# Initial condition
initial_state:
  site_index: 51 # start the exciton at site |51>


# Solver selection
solver:
  method: Lindblad # 'Lindblad' or 'NonHermitian'


  # Output file (goes under Hydra's run dir)
output:
  filename: ${material.name}_stationary_latest.hdf5