# Minimal defaults just to name the job
defaults:
  - hydra: default #<- This loads configs/Lindblad/hydra/default.yaml
  - _self_

hydra:
  job:
    name: NHSE_disorder

# --- Inputs (adjust the path or use oc.env as needed) ---
greens:
  h5_path: ${oc.env:MQED_ROOT,${oc.env:PWD}}/data/GF_cache/result_Ag_2_nm_latest.hdf5

# Material information
material:
  name: silver

# --- Simulation controls ---
simulation:
  t_ps:
    start: 0.0
    stop: 150.0
    output_step: 2e-3

  Nmol: 100
  d_nm: 3.0

  # orientation
  mu_D_debye: 3.8
  mu_A_debye: 3.8
  theta_deg: 90.0
  phi_deg: magic
  mode: disorder
  disorder_sigma_phi_deg: 10.0   # <-- set your sigma here

# Initial condition
initial_state:
  site_index: 51  # middle excitation.

# NHSE is faster and sufficient
solver:
  method: NonHermitian

# Ensemble averaging knobs
disorder:
  n_realizations: 80
  seed: 2025
  n_jobs: -1         # processes for parallel run (joblib). set to 1 to disable
  save_each: false   # true = save per-realization files too

output:
  filename: ${material.name}_sigma${simulation.disorder_sigma_phi_deg}_avg_latest.hdf5
